/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package TugasAkhir;
import com.mysql.jdbc.Statement;
import java.util.logging.Logger;
import java.awt.Color;
import java.text.DecimalFormat;
import java.text.NumberFormat;
import java.util.logging.Level;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

import java.io.File;
import java.util.HashMap;
import java.util.Map;
import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.JasperCompileManager;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.engine.design.JasperDesign;
import net.sf.jasperreports.engine.util.JRLoader;
import net.sf.jasperreports.engine.xml.JRXmlLoader;
import net.sf.jasperreports.view.JasperViewer;
/**
 *
 * @author Kelompok 3
 */
public class tokoelectronic extends javax.swing.JFrame {
    
    String kode = "" ;
    String pilihan = "" ;
    String nama_phone;
    String cara, nama,pp,tanggal,tgl,bulan,bln,tahun,th;
    int harga_phone;
    int harga_aks;
    int harga, bayar, beli,hargaaks,bayaraks,beliaks,total, metode;
    int Ang, Angg,Anggg,akhir;
    int kredit,ptx;
    
    DefaultTableModel model;
    
   
    
    public tokoelectronic() {
       initComponents();
       String [] judul ={"Tanggal", "Pembeli","Barang", "Pembayaran", "Total"};
       model = new DefaultTableModel(judul,0);
       tabel.setModel(model);
       KoneksiDatabase();
        }
   

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        buttonGroup3 = new javax.swing.ButtonGroup();
        buttonGroup4 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        filler1 = new javax.swing.Box.Filler(new java.awt.Dimension(200, 0), new java.awt.Dimension(200, 0), new java.awt.Dimension(200, 32767));
        jPanel1 = new javax.swing.JPanel();
        txthargaphone = new javax.swing.JTextField();
        tblHitungPhone = new javax.swing.JButton();
        tblBatalPhone = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        comboKode = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        txtPhone = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtSatuanPhone = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtBeliPhone = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        btnCash = new javax.swing.JRadioButton();
        btnTf = new javax.swing.JRadioButton();
        btnKredit = new javax.swing.JRadioButton();
        jLabel12 = new javax.swing.JLabel();
        txtRekening = new javax.swing.JTextField();
        btn9Ang = new javax.swing.JRadioButton();
        txt9Ang = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        btn3Ang = new javax.swing.JRadioButton();
        txt3Ang = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        btn6Ang = new javax.swing.JRadioButton();
        txt6Ang = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        tblHitSim = new javax.swing.JButton();
        tblCetak = new javax.swing.JButton();
        txtPembeli = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel23 = new javax.swing.JLabel();
        comboTanggal = new javax.swing.JComboBox<>();
        comboBulan = new javax.swing.JComboBox<>();
        comboTahun = new javax.swing.JComboBox<>();
        jLabel25 = new javax.swing.JLabel();
        txthargaakhir = new javax.swing.JTextField();
        btnakhir = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        txtNama = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        txtHasil = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        txtKet = new javax.swing.JTextField();
        txtTgl = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        comboPilihan = new javax.swing.JComboBox<>();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        txtSatuanAks = new javax.swing.JTextField();
        jLabel28 = new javax.swing.JLabel();
        txtBeliAks = new javax.swing.JTextField();
        tblBatalAks = new javax.swing.JButton();
        tblHitungAks = new javax.swing.JButton();
        txtHargaAks = new javax.swing.JTextField();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        tblNew = new javax.swing.JButton();
        tblExit = new javax.swing.JButton();
        jPanel7 = new javax.swing.JPanel();
        jLabel22 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tabel = new javax.swing.JTable();
        tblcencel = new javax.swing.JButton();
        btnSave = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Times New Roman", 3, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("\"\" KELOMPOK 3 \"\"   ");

        jLabel2.setFont(new java.awt.Font("Times New Roman", 3, 24)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("****\"\" TOKO CELL \"\"****   ");

        filler1.setBackground(new java.awt.Color(0, 0, 0));
        filler1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        filler1.setCursor(new java.awt.Cursor(java.awt.Cursor.CROSSHAIR_CURSOR));

        jPanel1.setBackground(new java.awt.Color(102, 255, 51));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 255, 255), 5));

        txthargaphone.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N

        tblHitungPhone.setText("Hitung");
        tblHitungPhone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tblHitungPhoneActionPerformed(evt);
            }
        });

        tblBatalPhone.setText("Batal");
        tblBatalPhone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tblBatalPhoneActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jLabel4.setText("Kode Barang");

        comboKode.setBackground(new java.awt.Color(204, 204, 204));
        comboKode.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        comboKode.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pilih Kode", "Ap001", "Ap002", "Ap003", "Ap004", "Ap005", "Ap006", "Ap007", "Ap008", "Ap009", "Ap010", "Ss001", "Ss002", "Ss003", "Ss004", "Ss005", "Ss006", "Ss007", "Ss008", "Ss009", "Ss010" }));
        comboKode.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboKodeActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jLabel5.setText("Nama Barang");

        txtPhone.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N

        jLabel6.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jLabel6.setText("Harga Satuan");

        txtSatuanPhone.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N

        jLabel7.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jLabel7.setText("Jumlah Beli");

        txtBeliPhone.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N

        jLabel8.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jLabel8.setText("Total Harga");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(txthargaphone, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 201, Short.MAX_VALUE)
                                .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 201, Short.MAX_VALUE))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(tblBatalPhone)
                                    .addGap(27, 27, 27)
                                    .addComponent(tblHitungPhone))
                                .addComponent(txtBeliPhone, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(comboKode, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txtPhone)
                                .addComponent(txtSatuanPhone, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addContainerGap()))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(165, Short.MAX_VALUE)
                .addComponent(txthargaphone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addContainerGap()
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel4)
                        .addComponent(comboKode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel5)
                        .addComponent(txtPhone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel6)
                        .addComponent(txtSatuanPhone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel7)
                        .addComponent(txtBeliPhone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(tblHitungPhone)
                        .addComponent(tblBatalPhone))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addComponent(jLabel8)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        jPanel2.setBackground(new java.awt.Color(204, 0, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 255, 255), 5));

        jLabel11.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jLabel11.setText("Metode Pembayaran");

        buttonGroup1.add(btnCash);
        btnCash.setText("Cash");
        btnCash.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCashActionPerformed(evt);
            }
        });

        buttonGroup1.add(btnTf);
        btnTf.setText("Transfer");
        btnTf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTfActionPerformed(evt);
            }
        });

        buttonGroup1.add(btnKredit);
        btnKredit.setText("Kredit");

        jLabel12.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jLabel12.setText("No. Rekening");

        txtRekening.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtRekeningActionPerformed(evt);
            }
        });

        buttonGroup2.add(btn9Ang);
        btn9Ang.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        btn9Ang.setText("9 x Anggsuran");

        txt9Ang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt9AngActionPerformed(evt);
            }
        });

        jLabel14.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jLabel14.setText("/ bulan");

        buttonGroup2.add(btn3Ang);
        btn3Ang.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        btn3Ang.setText("3 x Anggsuran");
        btn3Ang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn3AngActionPerformed(evt);
            }
        });

        txt3Ang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt3AngActionPerformed(evt);
            }
        });

        jLabel15.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jLabel15.setText("/ bulan");

        buttonGroup2.add(btn6Ang);
        btn6Ang.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        btn6Ang.setText("6 x Anggsuran");

        txt6Ang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt6AngActionPerformed(evt);
            }
        });

        jLabel16.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jLabel16.setText("/ bulan");

        tblHitSim.setText("Hitung Simulasi");
        tblHitSim.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tblHitSimActionPerformed(evt);
            }
        });

        tblCetak.setText("Cetak Struk");
        tblCetak.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tblCetakActionPerformed(evt);
            }
        });

        txtPembeli.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        txtPembeli.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPembeliActionPerformed(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jLabel10.setText("Nama Pembeli");

        jLabel20.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jLabel20.setText("Tanggal Pembayaran");

        jPanel4.setBackground(new java.awt.Color(204, 51, 255));

        jLabel23.setIcon(new javax.swing.ImageIcon(getClass().getResource("/TugasAkhir/home.png"))); // NOI18N

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel23)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(23, Short.MAX_VALUE)
                .addComponent(jLabel23)
                .addGap(21, 21, 21))
        );

        comboTanggal.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Tanggal", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31" }));
        comboTanggal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboTanggalActionPerformed(evt);
            }
        });

        comboBulan.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Bulan", "Januari", "Februari", "Maret", "April", "Mei", "Juni", "Juli", "Agustus", "September", "Oktober", "November", "Desember" }));
        comboBulan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboBulanActionPerformed(evt);
            }
        });

        comboTahun.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Tahun", "2021", "2022", "2023", "2024", "2025", "2026", "2027", "2028", "2029", "2030" }));
        comboTahun.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboTahunActionPerformed(evt);
            }
        });

        jLabel25.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jLabel25.setText("Total Akhir");

        txthargaakhir.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        txthargaakhir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txthargaakhirActionPerformed(evt);
            }
        });

        btnakhir.setText("Hitung");
        btnakhir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnakhirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(btn9Ang)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txt9Ang, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(8, 8, 8)
                                .addComponent(jLabel14))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(btn6Ang)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txt6Ang, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(btn3Ang)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txt3Ang, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel15)
                                    .addComponent(jLabel16))))
                        .addGap(14, 14, 14))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(tblHitSim)
                        .addGap(18, 18, 18)
                        .addComponent(tblCetak)
                        .addGap(33, 33, 33))))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtRekening, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(txtPembeli, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnCash)
                                .addGap(18, 18, 18)
                                .addComponent(btnTf)
                                .addGap(18, 18, 18)
                                .addComponent(btnKredit))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(26, 26, 26)
                                .addComponent(comboTanggal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(comboBulan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(comboTahun, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel25, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(txthargaakhir, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnakhir)))
                        .addGap(0, 10, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel25)
                    .addComponent(txthargaakhir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnakhir))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel20)
                    .addComponent(comboTanggal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(comboBulan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(comboTahun, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(txtPembeli, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCash)
                    .addComponent(btnTf)
                    .addComponent(btnKredit)
                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtRekening, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tblCetak)
                            .addComponent(tblHitSim))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel15)
                            .addComponent(txt3Ang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn3Ang))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btn6Ang, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(txt6Ang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel16)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btn9Ang)
                            .addComponent(txt9Ang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel14)))
                    .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        txtNama.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        txtNama.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNamaActionPerformed(evt);
            }
        });

        jLabel17.setText("Kelompok 3 Cell");

        jLabel3.setFont(new java.awt.Font("Times New Roman", 2, 8)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Jl. Kamal Raya No.18, RT.6/RW.3, Cengkareng Tim., Kecamatan Cengkareng, Kota Jakarta Barat");

        jLabel19.setText("Nama Pembeli");

        jLabel13.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jLabel13.setText("Total");

        txtHasil.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        txtHasil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtHasilActionPerformed(evt);
            }
        });

        jLabel21.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jLabel21.setText("Keterangan");

        txtKet.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        txtKet.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtKetActionPerformed(evt);
            }
        });

        txtTgl.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/TugasAkhir/TTd.png"))); // NOI18N

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 331, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jLabel13, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel19, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 96, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtNama, javax.swing.GroupLayout.DEFAULT_SIZE, 227, Short.MAX_VALUE)
                            .addComponent(txtHasil)))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtKet, javax.swing.GroupLayout.DEFAULT_SIZE, 229, Short.MAX_VALUE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(64, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9)
                    .addComponent(txtTgl, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel17)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel19))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(txtHasil, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel21)
                    .addComponent(txtKet, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtTgl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel9))
        );

        jLabel18.setFont(new java.awt.Font("Times New Roman", 2, 14)); // NOI18N
        jLabel18.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel18.setText("Jl. Kamal Raya No.18, RT.6/RW.3, Cengkareng Tim., Kecamatan Cengkareng, Kota Jakarta Barat, Daerah Khusus Ibukota Jakarta 11730");

        jPanel5.setBackground(new java.awt.Color(255, 255, 51));
        jPanel5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 255, 255), 2));

        comboPilihan.setBackground(new java.awt.Color(204, 204, 204));
        comboPilihan.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        comboPilihan.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pilih Aksesoris", "1. Kartu perdana", "Telkomsel / As", "Xl", "Tri", "Axis", "Indosat / M3", "By U", "SmartFren", "2. Aksesoris Hp", "Earphone", "Headseat", "Kabel Data Micro", "Kabel Data Type C", "Earphone bluetuoth", "SoftCase Hp ", "HardCase Hp", "Adapter 2A", "Adapter 4A" }));
        comboPilihan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboPilihanActionPerformed(evt);
            }
        });

        jLabel26.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jLabel26.setText("Pilih Aksesoris");

        jLabel27.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jLabel27.setText("Harga Satuan");

        txtSatuanAks.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N

        jLabel28.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jLabel28.setText("Jumlah Beli");

        txtBeliAks.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N

        tblBatalAks.setText("Batal");
        tblBatalAks.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tblBatalAksActionPerformed(evt);
            }
        });

        tblHitungAks.setText("Hitung");
        tblHitungAks.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tblHitungAksActionPerformed(evt);
            }
        });

        txtHargaAks.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N

        jLabel29.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jLabel29.setText("Total Harga");

        jLabel30.setFont(new java.awt.Font("Times New Roman", 2, 14)); // NOI18N
        jLabel30.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel30.setText("Aksesoris Hp Kelompok 3 Cell");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jLabel28, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel27, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel26, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 201, Short.MAX_VALUE)
                    .addComponent(jLabel29, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(tblBatalAks)
                        .addGap(18, 18, 18)
                        .addComponent(tblHitungAks)
                        .addGap(0, 72, Short.MAX_VALUE))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(comboPilihan, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(txtHargaAks, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtBeliAks, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtSatuanAks, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE))
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addContainerGap())))
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel30, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel30)
                .addGap(14, 14, 14)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel26)
                    .addComponent(comboPilihan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel27)
                    .addComponent(txtSatuanAks, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel28)
                    .addComponent(txtBeliAks, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tblBatalAks)
                    .addComponent(tblHitungAks))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtHargaAks, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel29))
                .addContainerGap())
        );

        tblNew.setText("New");
        tblNew.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tblNewActionPerformed(evt);
            }
        });

        tblExit.setText("Exit");
        tblExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tblExitActionPerformed(evt);
            }
        });

        jPanel7.setBackground(new java.awt.Color(255, 255, 255));

        jLabel22.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel22.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel22.setText("Histori Penjualan Toko Cell");

        tabel.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4", "Title 5"
            }
        ));
        tabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tabel);

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 349, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                        .addComponent(jLabel22, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(54, 54, 54))))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jLabel22)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(114, Short.MAX_VALUE))
        );

        tblcencel.setText("Cencel");
        tblcencel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tblcencelActionPerformed(evt);
            }
        });

        btnSave.setText("Save");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 844, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 844, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(filler1, javax.swing.GroupLayout.PREFERRED_SIZE, 910, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addGroup(layout.createSequentialGroup()
                                            .addGap(0, 39, Short.MAX_VALUE)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(tblcencel)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(tblNew)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                            .addComponent(btnSave)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                            .addComponent(tblExit)))))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 844, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, 367, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel18)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(filler1, javax.swing.GroupLayout.PREFERRED_SIZE, 13, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(tblNew)
                                    .addComponent(tblExit)
                                    .addComponent(tblcencel)
                                    .addComponent(btnSave)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(615, 649, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tblHitungPhoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tblHitungPhoneActionPerformed
        // TODO add your handling code here:
        harga = Integer.parseInt(txtSatuanPhone.getText());
        beli = Integer.parseInt(txtBeliPhone.getText());
        
        bayar = harga * beli;
       
        DecimalFormat angka = new DecimalFormat("###,###");
        txthargaphone.setText(""+Integer.toString(bayar));
    }//GEN-LAST:event_tblHitungPhoneActionPerformed

    private void btnCashActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCashActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCashActionPerformed

    private void txtRekeningActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtRekeningActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtRekeningActionPerformed

    private void txtHasilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtHasilActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtHasilActionPerformed

    private void btnTfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnTfActionPerformed

    private void txt9AngActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt9AngActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt9AngActionPerformed

    private void txt3AngActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt3AngActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt3AngActionPerformed

    private void txt6AngActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt6AngActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt6AngActionPerformed

    private void txtKetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtKetActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtKetActionPerformed

    private void tblHitungAksActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tblHitungAksActionPerformed
        // TODO add your handling code here:
        hargaaks = Integer.parseInt(txtSatuanAks.getText());
        beliaks = Integer.parseInt(txtBeliAks.getText());
        
        bayaraks = hargaaks * beliaks;
       
        DecimalFormat angka = new DecimalFormat("###,###");
        txtHargaAks.setText(""+Integer.toString(bayaraks));
        
    }//GEN-LAST:event_tblHitungAksActionPerformed

    private void tblBatalAksActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tblBatalAksActionPerformed
        // TODO add your handling code here:
        txtSatuanAks.setText("");
        txtBeliAks.setText("");
        txtHargaAks.setText("");
    }//GEN-LAST:event_tblBatalAksActionPerformed
    
    
    private void comboKodeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboKodeActionPerformed
        // TODO add your handling code here:
        kode = (String) comboKode.getSelectedItem();
        switch (kode){
                case "Ap001":
                    nama_phone = "Iphone 12 Mini";
                    harga_phone = 15000000;
                    break;
                case "Ap002":
                    nama_phone = "Iphone 12";
                    harga_phone = 18990000;
                    break;    
                case "Ap003":
                    nama_phone = "Iphone 12 Pro";
                    harga_phone = 19999000;
                    break;
                case "Ap004":
                    nama_phone = "Iphone 12 Pro Max";
                    harga_phone = 21000000;
                    break;
                case "Ap005":
                    nama_phone = "Iphone 11 Mini";
                    harga_phone = 16390000;
                    break;
                case "Ap006":
                    nama_phone = "Iphone 11";
                    harga_phone = 17490000;
                    break;    
                case "Ap007":
                    nama_phone = "Iphone 11 Pro";
                    harga_phone = 18499000;
                    break;
                case "Ap008":
                    nama_phone = "Iphone 11 Pro Max";
                    harga_phone = 19499000;
                    break;
                case "Ap009":
                    nama_phone = "Iphone 10 ";
                    harga_phone = 12100000;
                    break;
                case "Ap010":
                    nama_phone = "Iphone 10s";
                    harga_phone = 12900000;
                    break;
                case "Ss001":
                    nama_phone = "Galaxy S21 Ultra 5G";
                    harga_phone = 18999000;
                    break;
                case "Ss002":
                    nama_phone = "Galaxy Z Fold 2 5G";
                    harga_phone = 32499000;
                    break;    
                case "Ss003":
                    nama_phone = "Galaxy Note 20 Ultra 8/256";
                    harga_phone = 14999000;
                    break;
                case "Ss004":
                    nama_phone = "Galaxy S20 Ultra";
                    harga_phone = 13890000;
                    break;
                case "Ss005":
                    nama_phone = "Galaxy S20 FE";
                    harga_phone = 8899000;
                    break;
                case "Ss006":
                    nama_phone = "Galaxy A72";
                    harga_phone = 5899000;
                    break;    
                case "Ss007":
                    nama_phone = "Galaxy A12";
                    harga_phone = 2789000;
                    break;
                case "Ss008":
                    nama_phone = "Galaxy A02 4Gb";
                    harga_phone = 1999000;
                    break;
                case "Ss009":
                    nama_phone = "Galaxy A10s ";
                    harga_phone = 1399000;
                    break;
                case "Ss010":
                    nama_phone = "Galaxy A01 Core 2Gb";
                    harga_phone = 1149000;
                    break;    
        }
        txtPhone.setText(nama_phone);
        txtSatuanPhone.setText(""+Integer.toString(harga_phone));
    }//GEN-LAST:event_comboKodeActionPerformed

    private void comboPilihanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboPilihanActionPerformed
        // TODO add your handling code here:
        pilihan = (String) comboPilihan.getSelectedItem();
        switch (pilihan){
                case "Telkomsel / As":
                    harga_aks = 20000;
                    break;
                case "Xl":
                    harga_aks = 20000;
                    break;    
                case "Tri":
                    harga_aks = 15000;
                    break;
                case "Axis":
                    harga_aks = 15000;
                    break;
                case "Indosat / M3":
                    harga_aks = 15000;
                    break;
                case "By U":
                    harga_aks = 13000;
                    break;    
                case "Smartfren":
                    harga_aks = 18000;
                    break;
                case "Earphone":
                    harga_aks = 29000;
                    break;
                case "Headset":
                    harga_aks = 45000;
                    break;
                case "Kabel Data Micro":
                    harga_aks = 15000;
                    break;
                case "Kabel Data Type C":
                    harga_aks = 15000;
                    break;
                case "Earphone bluetuoth":
                    harga_aks = 75000;
                    break;
                case "SoftCase Hp ":
                    harga_aks = 25000;
                    break;
                case "HardCase Hp":
                    harga_aks = 35000;
                    break;    
                case "Adapter 2A":
                    harga_aks = 35000;
                    break;
                case "Adapter 4A":
                    harga_aks = 55000;
                    break;    
        }
        txtSatuanAks.setText(""+Integer.toString(harga_aks));
    }//GEN-LAST:event_comboPilihanActionPerformed

    private void txthargaakhirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txthargaakhirActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txthargaakhirActionPerformed

    private void btnakhirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnakhirActionPerformed
        // TODO add your handling code here:
        total = bayar + bayaraks;
        kredit = (total*20)/100;
        txthargaakhir.setText("Rp. "+Integer.toString(total)+" ,-");
    }//GEN-LAST:event_btnakhirActionPerformed

    private void tblHitSimActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tblHitSimActionPerformed
        // TODO add your handling code here:
        
        Ang = total / 3;
        Angg = total / 6;
        Anggg = total / 9;
        
        if (btn3Ang.isSelected()){
            metode = Ang;
        txt3Ang.setText("Rp. "+Integer.toString(metode)+" ,-");
        }
        else if (btn6Ang.isSelected()){
            metode = Angg;
        txt6Ang.setText("Rp. "+Integer.toString(metode)+" ,-");
        }
        else if (btn9Ang.isSelected()){
            metode = Anggg;
        txt9Ang.setText("Rp. "+Integer.toString(metode)+" ,-");
        }
        //pembatas
        if( btnCash.isSelected()){
            cara = "Cash";
            akhir = total;
            pp = "Lunas Cash";
        }
        else if(btnTf.isSelected()){
            cara = "7126132391 (BCA)";
            akhir = total;
            pp = "Lunas Via Transfer";
        }
        else if(btnKredit.isSelected()){
            cara = "7126132391 (BCA)";
            akhir = (kredit + metode);
            pp = "Dp Kredit Hp";
        }
        txtRekening.setText(cara);
       
       
    }//GEN-LAST:event_tblHitSimActionPerformed

    private void txtPembeliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPembeliActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPembeliActionPerformed

    private void btn3AngActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn3AngActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn3AngActionPerformed

    private void txtNamaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNamaActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_txtNamaActionPerformed

    private void tblCetakActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tblCetakActionPerformed
        // TODO add your handling code here:
       String nama = txtPembeli.getText();
       txtNama.setText(nama);
       txtHasil.setText("Rp. "+Integer.toString(akhir)+" ,-");
       txtKet.setText(pp);
       txtTgl.setText(tgl+" "+bln+" "+th);
        
    }//GEN-LAST:event_tblCetakActionPerformed

    private void comboTanggalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboTanggalActionPerformed
        // TODO add your handling code here:
        tanggal = (String)comboTanggal.getSelectedItem();
        switch (tanggal){
                case "1":
                    tgl="1";
                    break;
                case "2":
                    tgl="2";
                    break;    
                case "3":
                    tgl="3";
                    break;
                case "4":
                    tgl="4";
                    break;
                case "5":
                    tgl="5";
                    break;
                case "6":
                    tgl="6";
                    break;
                case "7":
                    tgl="7";
                    break;    
                case "8":
                    tgl="8";
                    break;
                case "9":
                    tgl="9";
                    break;
                case "10":
                    tgl="10";
                    break;    
                case "11":
                    tgl="11";
                    break;
                case "12":
                    tgl="12";
                    break;
                case "13":
                    tgl="13";
                    break;
                case "14":
                    tgl="14";
                    break;
                case "15":
                    tgl="15";
                    break;
                case "16":
                    tgl="16";
                    break;
                case "17":
                    tgl="17";
                    break;
                case "18":
                    tgl="18";
                    break;    
                case "19":
                    tgl="19";
                    break;
                case "20":
                    tgl="20";
                    break;
                case "21":
                    tgl="21";
                    break;
                case "22":
                    tgl="22";
                    break;    
                case "23":
                    tgl="23";
                    break;
                case "24":
                    tgl="24";
                    break;
                case "25":
                    tgl="25";
                    break;    
                case "26":
                    tgl="26";
                    break;
                case "27":
                    tgl="27";
                    break;    
                case "28":
                    tgl="28";
                    break;
                case "29":
                    tgl="29";
                    break;
                case "30":
                    tgl="30";
                    break;
                case "31":
                    tgl="31";
                    break;    
        }
    }//GEN-LAST:event_comboTanggalActionPerformed

    private void comboBulanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboBulanActionPerformed
        // TODO add your handling code here:
       bulan = (String)comboBulan.getSelectedItem();
        switch (bulan){
                case "Januari":
                    bln="Januari";
                    break;
                case "Februari":
                    bln="Februari";
                    break;    
                case "Maret":
                    bln="Maret";
                    break;
                case "April":
                    bln="April";
                    break;
                case "Mei":
                    bln="Mei";
                    break;
                case "Juni":
                    bln="Juni";
                    break;
                case "July":
                    bln="July";
                    break;    
                case "Agustus":
                    bln="Agustus";
                    break;
                case "September":
                    bln="september";
                    break;
                case "Oktober":
                    bln="Oktober";
                    break;    
                case "November":
                    bln="November";
                    break;
                case "Desember":
                    bln="Desember";
                    break; 
    }//GEN-LAST:event_comboBulanActionPerformed
}
    private void comboTahunActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboTahunActionPerformed
        // TODO add your handling code here:
        tahun = (String)comboTahun.getSelectedItem();
        switch (tahun){
                case "2021":
                    th="2021";
                    break;
                case "2022":
                    th="2022";
                    break;    
                case "2023":
                    th="2023";
                    break;
                case "2024":
                    th="2024";
                    break;
                case "2025":
                    th="2025";
                    break;
                case "2026":
                    th="2026";
                    break;
                case "2027":
                    th="2027";
                    break;    
                case "2028":
                    th="2028";
                    break;
                case "2029":
                    th="2029";
                    break;
                case "2030":
                    th="2030";
                    break;    
    }//GEN-LAST:event_comboTahunActionPerformed
}
    private void tblExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tblExitActionPerformed
        // TODO add your handling code here:
          System.exit(0);
    }//GEN-LAST:event_tblExitActionPerformed

    private void tblNewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tblNewActionPerformed
        // TODO add your handling code here:
        comboKode.removeItem("");
        comboPilihan.removeItem("");
        txtSatuanAks.setText("");
        txtBeliAks.setText("");
        txtHargaAks.setText("");
        txtPhone.setText("");
        txtSatuanPhone.setText("");
        txtBeliPhone.setText("");
        txthargaphone.setText("");
        txthargaakhir.setText("");
        txtPembeli.setText("");
        txtRekening.setText("");
        txt3Ang.setText("");
        txt6Ang.setText("");
        txt9Ang.setText("");
        txtNama.setText("");
        txtHasil.setText("");
        txtKet.setText("");
        txtTgl.setText("");
        buttonGroup2.clearSelection();
        buttonGroup1.clearSelection();
    }//GEN-LAST:event_tblNewActionPerformed

    private void tblBatalPhoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tblBatalPhoneActionPerformed
        // TODO add your handling code here:
        txtPhone.setText("");
        txtSatuanPhone.setText("");
        txtBeliPhone.setText("");
        txthargaphone.setText("");
    }//GEN-LAST:event_tblBatalPhoneActionPerformed

    private void tblcencelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tblcencelActionPerformed
        // TODO add your handling code here:
        txthargaakhir.setText("");
        txtPembeli.setText("");
        txtRekening.setText("");
        txt3Ang.setText("");
        txt6Ang.setText("");
        txt9Ang.setText("");
        txtNama.setText("");
        txtHasil.setText("");
        txtKet.setText("");
        txtTgl.setText("");
        buttonGroup2.clearSelection();
        buttonGroup1.clearSelection();
        
        
        
    }//GEN-LAST:event_tblcencelActionPerformed

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        try {
            // TODO add your handling code here:
            Connection cn = DriverManager.getConnection("jdbc:mysql://localhost:3306/database_cell", "root", "");
            cn.createStatement().executeUpdate("insert into cell values"+"('"+txtTgl.getText()+"','"+txtNama.getText()+"','"+txtPhone.getText()+"','"+txtKet.getText()+"','"+txtHasil.getText()+"')");
            KoneksiDatabase();
            JOptionPane.showMessageDialog(null, "Data Sudah DiSimpan");
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null," ANDA BELUM CONNECT MYSQL !!");
        }
        
    }//GEN-LAST:event_btnSaveActionPerformed

    private void tabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelMouseClicked
        // TODO add your handling code here:
        int i = tabel.getSelectedRow();
        
        if(i>-1){
            txtTgl.setText(model.getValueAt(i,0).toString());
            txtNama.setText(model.getValueAt(i,1).toString());
            txtPhone.setText(model.getValueAt(i,2).toString());
            txtKet.setText(model.getValueAt(i,3).toString());
            txtHasil.setText(model.getValueAt(i,4).toString());
            
        }
    }//GEN-LAST:event_tabelMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String[]args)throws SQLException, ClassNotFoundException{
        /* Set the Nimbus look and feel */
       
    //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
       
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new tokoelectronic().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton btn3Ang;
    private javax.swing.JRadioButton btn6Ang;
    private javax.swing.JRadioButton btn9Ang;
    private javax.swing.JRadioButton btnCash;
    private javax.swing.JRadioButton btnKredit;
    private javax.swing.JButton btnSave;
    private javax.swing.JRadioButton btnTf;
    private javax.swing.JButton btnakhir;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.ButtonGroup buttonGroup3;
    private javax.swing.ButtonGroup buttonGroup4;
    private javax.swing.JComboBox<String> comboBulan;
    private javax.swing.JComboBox<String> comboKode;
    private javax.swing.JComboBox<String> comboPilihan;
    private javax.swing.JComboBox<String> comboTahun;
    private javax.swing.JComboBox<String> comboTanggal;
    private javax.swing.Box.Filler filler1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tabel;
    private javax.swing.JButton tblBatalAks;
    private javax.swing.JButton tblBatalPhone;
    private javax.swing.JButton tblCetak;
    private javax.swing.JButton tblExit;
    private javax.swing.JButton tblHitSim;
    private javax.swing.JButton tblHitungAks;
    private javax.swing.JButton tblHitungPhone;
    private javax.swing.JButton tblNew;
    private javax.swing.JButton tblcencel;
    private javax.swing.JTextField txt3Ang;
    private javax.swing.JTextField txt6Ang;
    private javax.swing.JTextField txt9Ang;
    private javax.swing.JTextField txtBeliAks;
    private javax.swing.JTextField txtBeliPhone;
    private javax.swing.JTextField txtHargaAks;
    private javax.swing.JTextField txtHasil;
    private javax.swing.JTextField txtKet;
    private javax.swing.JTextField txtNama;
    private javax.swing.JTextField txtPembeli;
    private javax.swing.JTextField txtPhone;
    private javax.swing.JTextField txtRekening;
    private javax.swing.JTextField txtSatuanAks;
    private javax.swing.JTextField txtSatuanPhone;
    private javax.swing.JTextField txtTgl;
    private javax.swing.JTextField txthargaakhir;
    private javax.swing.JTextField txthargaphone;
    // End of variables declaration//GEN-END:variables
 private void KoneksiDatabase(){
        int row = tabel.getRowCount();
        for(int a=0; a<row;a++)
            model.removeRow(0);
        try {
           
            Connection cn = DriverManager.getConnection("jdbc:mysql://localhost:3306/database_cell", "root", "");
            ResultSet rs = cn.createStatement().executeQuery("SELECT * FROM cell");
            while (rs.next()){
                String data [] = {rs.getString(1),rs.getString(2),rs.getString(3),rs.getString(4),rs.getString(5)};
                model.addRow(data);
            }              
        }
        catch (SQLException ex) {
            Logger.getLogger(tokoelectronic.class.getName()).log(Level.SEVERE, null, ex);
        }

}
}
 
 
